spring:
    application:
        name: store
stripe:
    apiUrl: https://api.stripe.com
    enabled: true
    timeout: 1000
    supported-currencies: USD, EUR, GBP, BO
payment-gateway: paypal
email:
    host: http://smtp.email.com
    port: 21
