spring:
    application:
        name: store
    datasource:
        url: jdbc:mysql://localhost:3306/store_tmp?createDatabaseIfNotExist=true
        username: root
        password: MyPassword
jpa:
    hibernate:
        ddl-auto: create
